apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly
  namespace: shop
  labels:
    app: wildfly
spec:
  selector:
    matchLabels:
      app: wildfly
  replicas: 2
  template: 
    metadata:
      labels:
        app: wildfly
    spec:
      serviceAccountName: jgroups-kubeping-service-account
      containers:
        - name: kube-ping
          image: mmagnani/wildfly20-kubeping:latest
          command: ["/opt/jboss/wildfly/bin/standalone.sh"]
          args: ["--server-config", "standalone-full-ha.xml", "-b", $(POD_IP), "-bmanagement", $(POD_IP) ,"-bprivate", $(POD_IP) ]
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9990
            - containerPort: 7600
            - containerPort: 8888
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_LABELS 
              value: app=wildfly
            - name: JAVA_OPTS
              value: -Djdk.tls.client.protocols=TLSv1.3
---
apiVersion: v1
kind: Service
metadata:
    name: wildfly
    namespace: shop
    labels:
      app: wildfly
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    app: wildfly