apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly
  labels:
    app: wildfly
spec:
  selector:
    matchLabels:
      app: wildfly
  replicas: 2
  template: 
    metadata:
      labels:
        app: wildfly
    spec:
      serviceAccountName: jgroups-kubeping-service-account
      containers:
        - name: wildfly-kube-ping
          image: accordion/wildfly-kubeping:23
          command: ["/opt/jboss/wildfly/bin/standalone.sh"]
          args: ["--server-config", "standalone-ha.xml", "-b", $(POD_IP), "-bmanagement", $(POD_IP) ,"-bprivate", $(POD_IP) ]
          resources:
            requests:
              memory: 256Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 7600
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_LABELS 
              value: app=wildfly
---
apiVersion: v1
kind: Service
metadata:
    name: wildfly
    labels:
      app: wildfly
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    app: wildfly